### ISSUE TITLE
Error message

### ISSUE THREAD

**Issue by frankbracq** [D-Jeffrey/gedcom-to-visualmap#1]
Hi

I'm trying to process attached .ged file 
[test.ged.zip](https://github.com/D-Jeffrey/gedcom-to-visualmap/files/10425855/test.ged.zip) 
with 'python gedcom-to-map.py test.ged test.kml -noheatmap'. I'm getting this error message:

'Traceback (most recent call last):
  File "/Users/Frank/Documents/GitHub/gedcom-to-visualmap/gedcom-to-map/gedcom-to-map.py", line 73, in <module>
    Geoheatmap(myGeoOptions)
  File "/Users/Frank/Documents/GitHub/gedcom-to-visualmap/gedcom-to-map/gedcomvisual.py", line 67, in Geoheatmap
    humans = ParseAndGPS(gOp)
  File "/Users/Frank/Documents/GitHub/gedcom-to-visualmap/gedcom-to-map/gedcomvisual.py", line 108, in ParseAndGPS
    lookupresults.saveAddressCache()
  File "/Users/Frank/Documents/GitHub/gedcom-to-visualmap/gedcom-to-map/kml/gpslookup.py", line 166, in saveAddressCache
    for a in range(0,len(self.addresslist)):
TypeError: object of type 'NoneType' has no len()'

Can you help me? Thanks in advance

Frank
<img width="1263" alt="screenshot" src="https://user-images.githubusercontent.com/35921662/212680532-84bc3725-f351-4d73-ac45-dc983b5dd317.png">

**Comment by D-Jeffrey** [comment]
Sorry for not getting back to you quicker.  I never noticed that I had people looking at the project.  Never had watcherers or Stars before.  Never tried running on a MAC.  Let's see what we got.  There is nothing like coming back to code you created a while and ago and thinking... this is bad code...

Interesting, I don't have foreign or unicode characters in my addresses.

Somewhere along the way, I never tested without a cache file.

Okay, changed made... And merged in your changes and release 0.1.1

The GUI is a work in process, as you noticed.

Give that a looked interesting on google maps.  I prefer the HTML version, but both have +/-

![msedge_2023-03-13_21-13-25](https://user-images.githubusercontent.com/44452180/224891811-c204af3c-8b3e-457d-b322-dc62afaaf782.png)
